#if DOUBLES_ENABLED
#if COMPLEX_ENABLED
using System;

namespace Anathema.Vectors.Core
{
    //WARNING: Implementation generated by AI and not tested yet.
    /// <summary>
    /// Double precision doubleing point complex number
    /// </summary>
    public class dcom
    {
        public override bool Equals(object o)
        {
            if (o is dcom)
                return ((dcom)o) == this;
            else
                return false;
        }
        public double real { get; set; }
        public double imaginary { get; set; }

        public dcom()
        {

        }
        public dcom(double real, double imaginary)
        {
            this.real = real;
            this.imaginary = imaginary;
        }

        public dcom(double[] ri)
        {
            this.real = ri[0];
            this.imaginary = ri[1];
        }

        public static dcom operator +(dcom a, dcom b)
        {
            return new dcom(a.real + b.real, a.imaginary + b.imaginary);
        }
        public static dcom operator -(dcom a, dcom b)
        {
            return new dcom(a.real - b.real, a.imaginary - b.imaginary);
        }
        public static dcom operator *(dcom a, dcom b)
        {
            return new dcom((a.real * b.real) - (a.imaginary * b.imaginary),
                (a.real * b.imaginary) + (b.real * a.imaginary));
        }
        public static dcom operator /(dcom a, dcom b)
        {
            double denom = b.real * b.real + b.imaginary * b.imaginary;
            return new dcom(
                ((a.real * b.real) + (a.imaginary * b.imaginary)) / denom,
                ((a.imaginary * b.real) - (a.real * b.imaginary)) / denom
            );
        }
        public static dcom operator +(dcom a, double b)
        {
            return new dcom(a.real + b, a.imaginary);
        }
        public static dcom operator -(dcom a, double b)
        {
            return new dcom(a.real - b, a.imaginary);
        }
        public static dcom operator *(dcom a, double b)
        {
            return new dcom(a.real * b, a.imaginary * b);
        }
        public static dcom operator /(dcom a, double b)
        {
            return new dcom(a.real / b, a.imaginary / b);
        }

        public static dcom operator +(double a, dcom b)
        {
            return new dcom(a + b.real, b.imaginary);
        }
        public static dcom operator -(double a, dcom b)
        {
            return new dcom(a - b.real, -b.imaginary);
        }
        public static dcom operator *(double a, dcom b)
        {
            return new dcom(a * b.real, a * b.imaginary);
        }
        public static dcom operator /(double a, dcom b)
        {
            double denom = b.real * b.real + b.imaginary * b.imaginary;
            return new dcom(
                (a * b.real) / denom,
                (-a * b.imaginary) / denom
            );
        }


        public static bool operator !=(dcom a, dcom b)
        {
            return !(a == b);
        }
        public static bool operator ==(dcom a, dcom b)
        {
            if (!(a is null) && b is null)
                return false;
            if (a is null && !(b is null))
                return false;
            if (a is null && b is null)
                return true;
            return scalar.isClose(a.real, b.real) && scalar.isClose(a.imaginary, b.imaginary);
        }
    }
}
#endif
#endif